using Datalayer.Repository.IRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Library.App.Pages
{
    /// <summary>
    /// Interaction logic for Admin.xaml
    /// </summary>
    public partial class Admin : Page
    {
        private readonly IUnitOfWork _unitOfWork;
        public IEnumerable<Datalayer.Books> BookList { get; set; }
        public IEnumerable<Datalayer.Users> UserList { get; set; }
        public Admin(IUnitOfWork unitOfWork)
        {
            InitializeComponent();
            _unitOfWork = unitOfWork;
        }


        private void Page_Loaded(object sender, RoutedEventArgs e)
        {
            BookList = _unitOfWork.Book.GetAll();
            UserList = _unitOfWork.User.GetAll();
            dgvUsers.ItemsSource = UserList;
            dgvBooks.ItemsSource = BookList;
        }

        private void dgvUsers_AutoGeneratedColumns(object sender, EventArgs e)
        {
            if (dgvUsers.Columns.Count > 0)
            {
                dgvUsers.Columns.Where(a => a.Header.ToString() == "Id").First().Header = "کد";
                dgvUsers.Columns.Where(a => a.Header.ToString() == "UserName").First().Header = "نام کاربری";
                dgvUsers.Columns.Where(a => a.Header.ToString() == "Email").First().Header = "ایمیل";
                dgvUsers.Columns.Where(a => a.Header.ToString() == "Password").First().Header = "کلمه عبور";
                dgvUsers.Columns.Where(a => a.Header.ToString() == "isSpecial").First().Header = "کاربر ویژه";
                dgvUsers.Columns[5].Visibility = Visibility.Collapsed;
                dgvUsers.Columns[6].Visibility = Visibility.Collapsed;
            }
        }

        private void dgvBooks_AutoGeneratedColumns(object sender, EventArgs e)
        {
            if (dgvBooks.Columns.Count > 0)
            {
                dgvBooks.Columns.Where(a => a.Header.ToString() == "Id").First().Header = "کد";
                dgvBooks.Columns.Where(a => a.Header.ToString() == "BookName").First().Header = "نام کتاب";
                dgvBooks.Columns.Where(a => a.Header.ToString() == "Category").First().Header = "دسته بندی";
                dgvBooks.Columns.Where(a => a.Header.ToString() == "Price").First().Header = "قیمت";
                dgvBooks.Columns.Where(a => a.Header.ToString() == "Count").First().Header = "تعداد";
                dgvBooks.Columns.Where(a => a.Header.ToString() == "Likes").First().Header = "علاقه‌‌مندی";
                dgvBooks.Columns.Where(a => a.Header.ToString() == "Scores").First().Header = "امتیاز";
                dgvBooks.Columns.Where(a => a.Header.ToString() == "isSpecial").First().Header = "کتاب ویژه";
                dgvBooks.Columns.Where(a => a.Header.ToString() == "Date").First().Header = "تاریخ انتشار";
                dgvBooks.Columns[9].Visibility = Visibility.Collapsed;
                dgvBooks.Columns[10].Visibility = Visibility.Collapsed;
            }
        }
    }
}
